import express from 'express'; import cors from 'cors'; import dotenv from 'dotenv'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import multer from 'multer'; import Database from 'better-sqlite3'; import nodemailer from 'nodemailer'; import fs from 'fs'; import path from 'path'; import {fileURLToPath} from 'url';
dotenv.config(); const __dirname=path.dirname(fileURLToPath(import.meta.url)); const app=express(); const PORT=process.env.PORT||5000; const JWT_SECRET=process.env.JWT_SECRET||'dev-secret';
fs.mkdirSync(path.join(__dirname,'uploads'),{recursive:true}); const db=new Database(path.join(__dirname,'society.db')); db.pragma('foreign_keys = ON');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'resident'); CREATE TABLE IF NOT EXISTS complaints(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,category TEXT NOT NULL,description TEXT NOT NULL,photo TEXT,priority TEXT NOT NULL DEFAULT 'Medium',status TEXT NOT NULL DEFAULT 'Open',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,resolved_at TEXT,FOREIGN KEY(user_id) REFERENCES users(id)); CREATE TABLE IF NOT EXISTS history(id INTEGER PRIMARY KEY AUTOINCREMENT,complaint_id INTEGER NOT NULL,status TEXT NOT NULL,note TEXT,actor_id INTEGER NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(complaint_id) REFERENCES complaints(id) ON DELETE CASCADE,FOREIGN KEY(actor_id) REFERENCES users(id)); CREATE TABLE IF NOT EXISTS notices(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,body TEXT NOT NULL,important INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,author_id INTEGER NOT NULL,FOREIGN KEY(author_id) REFERENCES users(id));`);
const admin=db.prepare('SELECT id FROM users WHERE role=?').get('admin'); if(!admin){const p=bcrypt.hashSync('Admin@123',10); db.prepare('INSERT INTO users(name,email,password,role) VALUES(?,?,?,?)').run('Society Admin','admin@society.local',p,'admin');}
const upload=multer({storage:multer.diskStorage({destination:path.join(__dirname,'uploads'),filename:(r,f,cb)=>cb(null,Date.now()+'-'+f.originalname.replace(/[^a-zA-Z0-9._-]/g,'_'))}),limits:{fileSize:5*1024*1024}});
app.use(cors({origin:process.env.CLIENT_URL?.split(',')||true})); app.use(express.json()); app.use('/uploads',express.static(path.join(__dirname,'uploads'))); const now=()=>new Date().toISOString();
function auth(req,res,next){const h=req.headers.authorization||''; try{req.user=jwt.verify(h.replace('Bearer ',''),JWT_SECRET);next()}catch{return res.status(401).json({error:'Unauthorized'})}} function adminOnly(req,res,next){if(req.user.role!=='admin')return res.status(403).json({error:'Admin only'});next()}
async function mail(to,subject,text){if(!process.env.SMTP_HOST)return; const t=nodemailer.createTransport({host:process.env.SMTP_HOST,port:+(process.env.SMTP_PORT||587),secure:false,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}); await t.sendMail({from:process.env.MAIL_FROM,to,subject,text});}
app.post('/api/auth/register',async(req,res)=>{const {name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({error:'All fields required'});try{const hash=await bcrypt.hash(password,10);const x=db.prepare('INSERT INTO users(name,email,password) VALUES(?,?,?)').run(name,email,hash);const user={id:x.lastInsertRowid,name,email,role:'resident'};res.json({token:jwt.sign(user,JWT_SECRET),user})}catch{res.status(409).json({error:'Email already registered'})}});
app.post('/api/auth/login',async(req,res)=>{const {email,password}=req.body;const u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!(await bcrypt.compare(password,u.password)))return res.status(401).json({error:'Invalid credentials'});const user={id:u.id,name:u.name,email:u.email,role:u.role};res.json({token:jwt.sign(user,JWT_SECRET),user})});
app.get('/api/complaints',auth,(req,res)=>{const overdueDays=+(process.env.OVERDUE_DAYS||7);let rows=req.user.role==='admin'?db.prepare(`SELECT c.*,u.name resident,u.email FROM complaints c JOIN users u ON u.id=c.user_id ORDER BY CASE WHEN c.status!='Resolved' AND julianday('now')-julianday(c.created_at)>? THEN 0 ELSE 1 END,c.created_at DESC`).all(overdueDays):db.prepare('SELECT * FROM complaints WHERE user_id=? ORDER BY created_at DESC').all(req.user.id);rows=rows.map(c=>({...c,overdue:c.status!=='Resolved'&&((Date.now()-Date.parse(c.created_at))/86400000>overdueDays),history:db.prepare('SELECT h.*,u.name actor FROM history h JOIN users u ON u.id=h.actor_id WHERE complaint_id=? ORDER BY created_at DESC').all(c.id)}));res.json(rows)});
app.post('/api/complaints',auth,upload.single('photo'),async(req,res)=>{const {category,description}=req.body;if(!category||!description)return res.status(400).json({error:'Category and description required'});const t=now(),photo=req.file?`/uploads/${req.file.filename}`:null;const x=db.prepare('INSERT INTO complaints(user_id,category,description,photo,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(req.user.id,category,description,photo,t,t);db.prepare('INSERT INTO history(complaint_id,status,note,actor_id,created_at) VALUES(?,?,?,?,?)').run(x.lastInsertRowid,'Open','Complaint created',req.user.id,t);res.json({id:x.lastInsertRowid})});
app.patch('/api/complaints/:id',auth,adminOnly,async(req,res)=>{const c=db.prepare('SELECT c.*,u.email FROM complaints c JOIN users u ON u.id=c.user_id WHERE c.id=?').get(req.params.id);if(!c)return res.status(404).json({error:'Not found'});const status=req.body.status||c.status,priority=req.body.priority||c.priority,note=req.body.note||'';if(!['Open','In Progress','Resolved'].includes(status)||!['Low','Medium','High'].includes(priority))return res.status(400).json({error:'Invalid status or priority'});const t=now();db.prepare('UPDATE complaints SET status=?,priority=?,updated_at=?,resolved_at=? WHERE id=?').run(status,priority,t,status==='Resolved'?t:null,c.id);if(status!==c.status)db.prepare('INSERT INTO history(complaint_id,status,note,actor_id,created_at) VALUES(?,?,?,?,?)').run(c.id,status,note,req.user.id,t);if(status!==c.status){mail(c.email,`Complaint #${c.id} updated`,`Your complaint is now ${status}. ${note}`).catch(()=>{});}res.json({ok:true})});
app.get('/api/notices',auth,(req,res)=>res.json(db.prepare('SELECT n.*,u.name author FROM notices n JOIN users u ON u.id=n.author_id ORDER BY important DESC,created_at DESC').all()));
app.post('/api/notices',auth,adminOnly,async(req,res)=>{const {title,body,important}=req.body;if(!title||!body)return res.status(400).json({error:'Title and body required'});const t=now();const x=db.prepare('INSERT INTO notices(title,body,important,created_at,author_id) VALUES(?,?,?,?,?)').run(title,body,important?1:0,t,req.user.id);if(important){const residents=db.prepare('SELECT email FROM users WHERE role="resident"').all();for(const r of residents)mail(r.email,`Important notice: ${title}`,body).catch(()=>{});}res.json({id:x.lastInsertRowid})});
app.get('/api/dashboard',auth,adminOnly,(req,res)=>{const total=db.prepare('SELECT COUNT(*) n FROM complaints').get().n;const statuses=db.prepare('SELECT status,COUNT(*) n FROM complaints GROUP BY status').all();const categories=db.prepare('SELECT category,COUNT(*) n FROM complaints GROUP BY category').all();const overdue=db.prepare(`SELECT COUNT(*) n FROM complaints WHERE status!='Resolved' AND julianday('now')-julianday(created_at)>?`).get(+(process.env.OVERDUE_DAYS||7)).n;res.json({total,statuses,categories,overdue})});
app.listen(PORT,()=>console.log(`API running on ${PORT}`));
